---
- hosts: localhost # localhost
  gather_facts: true
  become: true
  become_user:
  vars:
    jenkins_hostname: 0.0.0.0
    jenkins_http_port: 8999
    jenkins_admin_username: admin
    jenkins_admin_password: admin
  tasks:
    - name: Import java and jenkins roles
      include_role:
        name: "{{ item }}"
      loop:
        - java
        - jenkins
